# Generated by Django 5.0.6 on 2024-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                ("url", models.CharField(max_length=255)),
                (
                    "collection_id",
                    models.UUIDField(
                        primary_key=True,
                    ),
                ),
            ],
        ),
    ]
