services:
  db:
    image: pgvector/pgvector:pg16
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  postgres:
  redis:
