from decouple import config

BUCKET_NAME = config("BUCKET_NAME")
DATABASE_URL = config("DATABASE_URL")
DOC_EXTENSIONS = [".txt"]
KEY_FILE_LOCATION = config("KEY_FILE_LOCATION")
OPENAI_BASE_URL = config("OPENAI_BASE_URL")
OPENAI_EMBEDDINGS_MODEL = config("OPENAI_EMBEDDINGS_MODEL")
