# Generated by Django 5.0.6 on 2024-06-26 04:04

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
